config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  root "home#index"

  scope controller: :webauthn, as: :webauthn, path: '/webauthn' do
    post :setup
    post :remove
    post :auth
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :user_agent, :ip_address

  delegate :user, to: :session, allow_nil: true
end

app/models/email_verification_token.rb
class EmailVerificationToken < ApplicationRecord
  belongs_to :user
end

app/models/password_reset_token.rb
class PasswordResetToken < ApplicationRecord
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user

  before_create do
    self.user_agent = Current.user_agent
    self.ip_address = Current.ip_address
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :email_verification_tokens, dependent: :destroy
  has_many :password_reset_tokens, dependent: :destroy
  has_many :sessions, dependent: :destroy
  has_many :webauthn_credentials, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 12 }

  before_validation if: -> { email.present? } do
    self.email = email.downcase.strip
  end

  before_validation if: :email_changed?, on: :update do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).delete_all
  end
end

app/models/webauthn_credential.rb
class WebauthnCredential < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_request_details
  before_action :authenticate

  private
    def authenticate
      if session_record = Session.find_by_id(cookies.signed[:session_token])
        Current.session = session_record
      else
        redirect_to sign_in_path
      end
    end

    def set_current_request_details
      Current.user_agent = request.user_agent
      Current.ip_address = request.ip
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @webauthn_params = RodauthMain.webauthn_setup_params(account_id: Current.user.id)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if !@user.authenticate(params[:current_password])
      redirect_to edit_password_path, alert: "The current password you entered is incorrect"
    elsif @user.update(user_params)
      redirect_to root_path, notice: "Your password has been changed"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_user
      @user = Current.user
    end

    def user_params
      params.permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session_record = @user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: session_record.id, httponly: true }

      send_email_verification
      redirect_to root_path, notice: "Welcome! You have signed up successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.permit(:email, :password, :password_confirmation)
    end

    def send_email_verification
      UserMailer.with(user: @user).email_verification.deliver_later
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: %i[ new create ]

  before_action :set_session, only: :destroy

  def index
    @sessions = Current.user.sessions.order(created_at: :desc)
  end

  def new
    @webauthn_params = RodauthMain.webauthn_login_params
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      @session = user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true }

      redirect_to root_path, notice: "Signed in successfully"
    else
      redirect_to sign_in_path(email_hint: params[:email]), alert: "That email or password is incorrect"
    end
  end

  def destroy
    @session.destroy; redirect_to(sessions_path, notice: "That session has been logged out")
  end

  private
    def set_session
      @session = Current.user.sessions.find(params[:id])
    end
end

app/controllers/webauthn_controller.rb
class WebauthnController < ApplicationController
  skip_before_action :authenticate, only: %i[auth]

  def setup
    RodauthMain.webauthn_setup(
      account_id: Current.user.id,
      webauthn_setup: params[:webauthn_setup],
      webauthn_setup_challenge: params[:webauthn_setup_challenge],
      webauthn_setup_challenge_hmac: params[:webauthn_setup_challenge_hmac],
      params: { 'nickname' => params[:nickname] }
    )

    redirect_to root_path, notice: 'Passkey successfully created.'
  rescue Rodauth::InternalRequestError => error
    redirect_to root_path, alert: ["Error creating a passkey", *error.field_errors.values.first].compact.join(" - ")
  end

  def remove
    RodauthMain.webauthn_remove(account_id: Current.user.id, webauthn_remove: params[:webauthn_id])

    redirect_to root_path, notice: "Passkey successfully removed"
  end

  def auth
    user_id = RodauthMain.webauthn_login(
      webauthn_auth: params[:webauthn_auth],
      webauthn_auth_challenge: params[:webauthn_auth_challenge],
      webauthn_auth_challenge_hmac: params[:webauthn_auth_challenge_hmac],
    )

    @session = Session.create!(user_id: user_id)
    cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true }

    redirect_to root_path, notice: 'Signed in successfully'
  rescue Rodauth::InternalRequestError => error
    redirect_to new_session_path, alert: ["Error authenticating with a passkey", *error.field_errors.values.first].compact.join(" - ")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webauthn_helper.rb
module WebauthnHelper
end

app/views/home/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<p>Signed as <%= Current.user.email %></p>

<h2>Login and verification</h2>

<div>
  <%= link_to "Change password", edit_password_path %>
</div>

<div>
  <%= link_to "Change email address", edit_identity_email_path %>
</div>

<h2>Passkeys</h2>

<ul>
  <% Current.user.webauthn_credentials.each do |webauthn_credential| %>
    <li>
      <%= webauthn_credential.nickname %>
      <%= form_with url: webauthn_remove_path, method: :post do |f| %>
        <%= f.hidden_field :webauthn_id, value: webauthn_credential.webauthn_id %>
        <%= f.submit "Delete" %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= form_with url: webauthn_setup_path, method: :post, data: { controller: 'webauthn', webauthn_data_value: @webauthn_params[:webauthn_setup].to_json } do |f| %>
  <%= f.hidden_field :webauthn_setup, data: { webauthn_target: "result" } %>
  <%= f.hidden_field :webauthn_setup_challenge, value: @webauthn_params[:webauthn_setup_challenge] %>
  <%= f.hidden_field :webauthn_setup_challenge_hmac, value: @webauthn_params[:webauthn_setup_challenge_hmac] %>

  <%= f.text_field :nickname, placeholder: 'e.g iCloud Key' %>

  <%= f.submit "Create Passkey", data: { action: "webauthn#setup:prevent" } %>
<% end %>

<% if @wehauthn_error %>
  <p>Passkey fail</p>
<% end %>

<h2>Access history</h2>

<div>
  <%= link_to "Devices & Sessions", sessions_path %>
</div>

<br>

<%= button_to "Log out", Current.session, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasskeysCustomAuthentications</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>